# Generated by Django 6.0 on 2026-01-21 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercerts', '0002_signing_history_revocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signinghistory',
            new_name='usercerts_s_user_id_e6a36e_idx',
            old_name='usercerts_s_user_id_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='signinghistory',
            new_name='usercerts_s_documen_0be963_idx',
            old_name='usercerts_s_documen_ghi789_idx',
        ),
        migrations.RenameIndex(
            model_name='signinghistory',
            new_name='usercerts_s_status_bb115c_idx',
            old_name='usercerts_s_status_jkl012_idx',
        ),
        migrations.RenameIndex(
            model_name='usercert',
            new_name='usercerts_u_user_id_5828bb_idx',
            old_name='usercerts_u_user_id_7b8c12_idx',
        ),
        migrations.RenameIndex(
            model_name='usercert',
            new_name='usercerts_u_serial__2e5ed9_idx',
            old_name='usercerts_u_serial__abc123_idx',
        ),
        migrations.AlterField(
            model_name='usercert',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
