# Generated by Django 5.2.10 on 2026-01-22 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercerts', '0003_rename_usercerts_s_user_id_def456_idx_usercerts_s_user_id_e6a36e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('CERT', 'Certificate'), ('SIGN', 'Signing'), ('ADMIN', 'Administration'), ('ACCESS', 'Access Control'), ('CONFIG', 'Configuration')], db_index=True, max_length=16)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_logs', 'Can view security audit logs'), ('export_audit_logs', 'Can export security audit logs')],
                'indexes': [models.Index(fields=['timestamp'], name='usercerts_s_timesta_aa4a92_idx'), models.Index(fields=['category', 'action'], name='usercerts_s_categor_a16678_idx'), models.Index(fields=['user', 'timestamp'], name='usercerts_s_user_id_3289a5_idx'), models.Index(fields=['username', 'timestamp'], name='usercerts_s_usernam_2382ae_idx'), models.Index(fields=['ip_address'], name='usercerts_s_ip_addr_53d3e7_idx'), models.Index(fields=['success', 'category'], name='usercerts_s_success_4d0610_idx')],
            },
        ),
    ]
