# Generated by Django 5.2.10 on 2026-01-25 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercerts', '0004_securityauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signinghistory',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signinghistory',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the stored file expires and can be deleted', null=True),
        ),
        migrations.AddField(
            model_name='signinghistory',
            name='file_path',
            field=models.CharField(blank=True, help_text='Relative path to signed PDF in SIGNED_PDF_STORAGE_DIR', max_length=1024),
        ),
        migrations.AddField(
            model_name='signinghistory',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signinghistory',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('deleted', 'Deleted')], db_index=True, default='valid', max_length=16),
        ),
        migrations.AddIndex(
            model_name='signinghistory',
            index=models.Index(fields=['expires_at'], name='usercerts_s_expires_ff07a9_idx'),
        ),
    ]
