# Generated by Django migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercerts', '0005_add_signed_pdf_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercert',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Certificate validity start date', null=True),
        ),
        migrations.AlterField(
            model_name='usercert',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Certificate expiration date', null=True),
        ),
    ]
