# Generated by Django 6.0.1 on 2026-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_update_signedpdf_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signedpdf',
            new_name='signing_sig_user_id_3ac19d_idx',
            old_name='signing_sig_user_id_signed_idx',
        ),
        migrations.RenameIndex(
            model_name='signedpdf',
            new_name='signing_sig_pdf_id_990377_idx',
            old_name='signing_sig_pdf_id_idx',
        ),
        migrations.RenameIndex(
            model_name='signedpdf',
            new_name='signing_sig_user_id_486ebc_idx',
            old_name='signing_sig_user_id_cached_idx',
        ),
    ]
