# Generated by Django 5.2.10 on 2026-01-23 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_userprofile_email_userprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or description', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('cntt', 'Khoa Công nghệ Thông tin'), ('dtvt', 'Khoa Điện tử Viễn thông'), ('cokhi', 'Khoa Cơ khí'), ('hoa', 'Khoa Hóa học'), ('kinhte', 'Khoa Kinh tế'), ('ngoaingu', 'Khoa Ngoại ngữ'), ('toan', 'Khoa Toán - Tin học'), ('vatly', 'Khoa Vật lý'), ('sinhhoc', 'Khoa Sinh học'), ('luat', 'Khoa Luật'), ('yte', 'Khoa Y tế'), ('other', 'Khác')], help_text='Department/Faculty', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email - may be included in certificate SAN', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name - may be used in certificate CN', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with optional country code', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('staff', 'Staff'), ('admin', 'Administrator')], default='student', help_text='User role for access control', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=256)),
                ('new_value', models.CharField(blank=True, max_length=256)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', 'changed_at'], name='usermanage__user_id_ce30d4_idx'), models.Index(fields=['field_name', 'changed_at'], name='usermanage__field_n_fd247a_idx')],
            },
        ),
    ]
