# Generated by Django 5.2.10 on 2026-01-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('cntt', 'Khoa Công nghệ Thông tin'), ('dien', 'Khoa Điện'), ('dtvt', 'Khoa Điện tử - Viễn thông'), ('cokhi', 'Khoa Cơ khí'), ('ckgt', 'Khoa Cơ khí Giao thông'), ('nhiet', 'Khoa Công nghệ Nhiệt - Điện lạnh'), ('hoa', 'Khoa Công nghệ Hóa học'), ('xddd', 'Khoa Xây dựng Dân dụng và Công nghiệp'), ('xdcd', 'Khoa Xây dựng Cầu đường'), ('xdtl', 'Khoa Xây dựng Thủy lợi - Thủy điện'), ('kientruc', 'Khoa Kiến trúc'), ('moitruong', 'Khoa Môi trường'), ('qlda', 'Khoa Quản lý Dự án'), ('fast', 'Khoa Khoa học Công nghệ Tiên tiến (FAST)'), ('khcb', 'Khoa Khoa học Cơ bản'), ('other', 'Khác')], help_text='Department/Faculty', max_length=32),
        ),
    ]
